spring:
  config:
    import: aws-parameterstore:/config/0younge/prod/

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: never

  info:
    env:
      enabled: true