spring:
  datasource:
    url: jdbc:mysql://localhost:3306/{database 이름}
    username: {user 이름}
    password: {user password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never